export enum BodyPart {
  Head = 'head',
  Neck = 'neck',
  LeftShoulder = 'left_shoulder',
  RightShoulder = 'right_shoulder',
  LeftChest = 'left_chest',
  RightChest = 'right_chest',
  LeftUpperArm = 'left_upper_arm',
  RightUpperArm = 'right_upper_arm',
  LeftForearm = 'left_forearm',
  RightForearm = 'right_forearm',
  LeftHand = 'left_hand',
  RightHand = 'right_hand',
  AbdomenUpper = 'abdomen_upper',
  AbdomenLower = 'abdomen_lower',
  UpperBack = 'upper_back',
  MiddleBack = 'middle_back',
  LowerBack = 'lower_back',
  LeftOblique = 'left_oblique',
  RightOblique = 'right_oblique',
  LeftHip = 'left_hip',
  RightHip = 'right_hip',
  LeftGlute = 'left_glute',
  RightGlute = 'right_glute',
  LeftQuadricep = 'left_quadricep',
  RightQuadricep = 'right_quadricep',
  LeftHamstring = 'left_hamstring',
  RightHamstring = 'right_hamstring',
  LeftInnerThigh = 'left_inner_thigh',
  RightInnerThigh = 'right_inner_thigh',
  LeftKnee = 'left_knee',
  RightKnee = 'right_knee',
  LeftCalf = 'left_calf',
  RightCalf = 'right_calf',
  LeftShin = 'left_shin',
  RightShin = 'right_shin',
  LeftAnkle = 'left_ankle',
  RightAnkle = 'right_ankle',
  LeftFoot = 'left_foot',
  RightFoot = 'right_foot',
}

export enum SensationType {
  Soreness = 'soreness',
  Tightness = 'tightness',
  Pain = 'pain',
  Fatigue = 'fatigue',
  Pump = 'pump',
  Stretch = 'stretch',
  Numbness = 'numbness',
  Warmth = 'warmth',
  Weakness = 'weakness',
  Strength = 'strength',
  Relaxation = 'relaxation',
  Other = 'other',
}

export const BODY_PART_LABELS: Record<BodyPart, string> = {
  [BodyPart.Head]: '头部',
  [BodyPart.Neck]: '颈部',
  [BodyPart.LeftShoulder]: '左肩',
  [BodyPart.RightShoulder]: '右肩',
  [BodyPart.LeftChest]: '左胸',
  [BodyPart.RightChest]: '右胸',
  [BodyPart.LeftUpperArm]: '左上臂',
  [BodyPart.RightUpperArm]: '右上臂',
  [BodyPart.LeftForearm]: '左前臂',
  [BodyPart.RightForearm]: '右前臂',
  [BodyPart.LeftHand]: '左手',
  [BodyPart.RightHand]: '右手',
  [BodyPart.AbdomenUpper]: '上腹',
  [BodyPart.AbdomenLower]: '下腹',
  [BodyPart.UpperBack]: '上背',
  [BodyPart.MiddleBack]: '中背',
  [BodyPart.LowerBack]: '下背/腰',
  [BodyPart.LeftOblique]: '左侧腹',
  [BodyPart.RightOblique]: '右侧腹',
  [BodyPart.LeftHip]: '左髋',
  [BodyPart.RightHip]: '右髋',
  [BodyPart.LeftGlute]: '左臀',
  [BodyPart.RightGlute]: '右臀',
  [BodyPart.LeftQuadricep]: '左股四头',
  [BodyPart.RightQuadricep]: '右股四头',
  [BodyPart.LeftHamstring]: '左腘绳肌',
  [BodyPart.RightHamstring]: '右腘绳肌',
  [BodyPart.LeftInnerThigh]: '左内侧',
  [BodyPart.RightInnerThigh]: '右内侧',
  [BodyPart.LeftKnee]: '左膝',
  [BodyPart.RightKnee]: '右膝',
  [BodyPart.LeftCalf]: '左小腿',
  [BodyPart.RightCalf]: '右小腿',
  [BodyPart.LeftShin]: '左胫骨',
  [BodyPart.RightShin]: '右胫骨',
  [BodyPart.LeftAnkle]: '左踝',
  [BodyPart.RightAnkle]: '右踝',
  [BodyPart.LeftFoot]: '左脚',
  [BodyPart.RightFoot]: '右脚',
}

export const SENSATION_LABELS: Record<SensationType, string> = {
  [SensationType.Soreness]: '酸痛',
  [SensationType.Tightness]: '紧绷',
  [SensationType.Pain]: '疼痛',
  [SensationType.Fatigue]: '疲劳',
  [SensationType.Pump]: '泵感',
  [SensationType.Stretch]: '拉伸感',
  [SensationType.Numbness]: '麻木',
  [SensationType.Warmth]: '温热',
  [SensationType.Weakness]: '无力',
  [SensationType.Strength]: '力量感',
  [SensationType.Relaxation]: '放松',
  [SensationType.Other]: '其他',
}

export const SENSATION_COLORS: Record<SensationType, string> = {
  [SensationType.Soreness]: '#FF6B6B',
  [SensationType.Tightness]: '#FFA94D',
  [SensationType.Pain]: '#FF0000',
  [SensationType.Fatigue]: '#868E96',
  [SensationType.Pump]: '#845EF7',
  [SensationType.Stretch]: '#20C997',
  [SensationType.Numbness]: '#495057',
  [SensationType.Warmth]: '#FD7E14',
  [SensationType.Weakness]: '#ADB5BD',
  [SensationType.Strength]: '#228BE6',
  [SensationType.Relaxation]: '#51CF66',
  [SensationType.Other]: '#CED4DA',
}

// 按区域分组的身体部位（用于 TagSelector）
export const BODY_PART_GROUPS: { label: string; parts: BodyPart[] }[] = [
  { label: '头颈', parts: [BodyPart.Head, BodyPart.Neck] },
  { label: '肩胸', parts: [BodyPart.LeftShoulder, BodyPart.RightShoulder, BodyPart.LeftChest, BodyPart.RightChest] },
  { label: '手臂', parts: [BodyPart.LeftUpperArm, BodyPart.RightUpperArm, BodyPart.LeftForearm, BodyPart.RightForearm, BodyPart.LeftHand, BodyPart.RightHand] },
  { label: '核心', parts: [BodyPart.AbdomenUpper, BodyPart.AbdomenLower, BodyPart.LeftOblique, BodyPart.RightOblique] },
  { label: '背部', parts: [BodyPart.UpperBack, BodyPart.MiddleBack, BodyPart.LowerBack] },
  { label: '臀髋', parts: [BodyPart.LeftHip, BodyPart.RightHip, BodyPart.LeftGlute, BodyPart.RightGlute] },
  { label: '大腿', parts: [BodyPart.LeftQuadricep, BodyPart.RightQuadricep, BodyPart.LeftHamstring, BodyPart.RightHamstring, BodyPart.LeftInnerThigh, BodyPart.RightInnerThigh] },
  { label: '膝小腿', parts: [BodyPart.LeftKnee, BodyPart.RightKnee, BodyPart.LeftCalf, BodyPart.RightCalf, BodyPart.LeftShin, BodyPart.RightShin] },
  { label: '踝脚', parts: [BodyPart.LeftAnkle, BodyPart.RightAnkle, BodyPart.LeftFoot, BodyPart.RightFoot] },
]
